import { useState } from 'react';

type Props = { angleStep: number; active: string; onSelect: (stage: string) => void };
const nodes = [{ id: 'feed', label: 'FEED', x: 84, y: 150, tone: 'gold' }, { id: 'crush', label: 'CRUSH', x: 248, y: 90, tone: 'teal' }, { id: 'grind', label: 'GRIND', x: 248, y: 210, tone: 'teal' }, { id: 'classify', label: 'CLASSIFY', x: 424, y: 150, tone: 'violet' }, { id: 'float', label: 'FLOTATION', x: 598, y: 150, tone: 'cyan' }, { id: 'product', label: 'CONCENTRATE', x: 790, y: 92, tone: 'gold' }, { id: 'tail', label: 'TAILINGS', x: 790, y: 218, tone: 'muted' }];
export default function Flowsheet({ angleStep, active, onSelect }: Props) {
  const [hover, setHover] = useState('');
  const selected = hover || active;
  return <div className="of-flowsheet-wrap"><svg className="of-flowsheet" viewBox="0 0 880 300" role="img" aria-label="Animated OreFlow circuit">
    <defs><linearGradient id="ore-path" x1="0" x2="1"><stop stopColor="#f0ba64" /><stop offset=".45" stopColor="#6cd5c6" /><stop offset="1" stopColor="#c586e8" /></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="b" /><feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
    <g className="of-flow-lines" fill="none" stroke="url(#ore-path)" strokeWidth="5" strokeLinecap="round"><path d="M108 150h74l44-60h-2" /><path d="M108 150h74l44 60h-2" /><path d="M272 90h90l50 60" /><path d="M272 210h90l50-60" /><path d="M448 150h112" /><path d="M622 150h90l55-58" /><path d="M622 150h90l55 68" /></g>
    <g className="of-particles" style={{ ['--particle-duration' as string]: `${Math.max(1.8, 6 - angleStep / 8)}s` }}><circle r="4" fill="#f0ba64"><animateMotion dur="var(--particle-duration)" repeatCount="indefinite" path="M108 150h74l44-60h90l50 60h112" /></circle><circle r="3" fill="#6cd5c6"><animateMotion dur="calc(var(--particle-duration) * 1.2)" begin="-.8s" repeatCount="indefinite" path="M108 150h74l44 60h90l50-60h112" /></circle><circle r="3" fill="#c586e8"><animateMotion dur="calc(var(--particle-duration) * .85)" begin="-1.4s" repeatCount="indefinite" path="M448 150h112l90-58h55" /></circle></g>
    {nodes.map(node => <g key={node.id} className={`of-flow-node ${selected === node.id ? 'is-active' : ''}`} onClick={() => onSelect(node.id)} onMouseEnter={() => setHover(node.id)} onMouseLeave={() => setHover('')} tabIndex={0} role="button" aria-label={node.label}><circle cx={node.x} cy={node.y} r="29" className={`of-node-circle ${node.tone}`} filter={selected === node.id ? 'url(#glow)' : undefined} /><circle cx={node.x} cy={node.y} r="20" className="of-node-inner" /><text x={node.x} y={node.y + 4} textAnchor="middle">{node.label.slice(0, 3)}</text><text x={node.x} y={node.y + 49} textAnchor="middle" className="of-node-label">{node.label}</text></g>)}
  </svg><div className="of-flow-caption"><span><i className="of-pulse" /> particles follow the active circuit</span><span>{selected.toUpperCase()} selected</span></div></div>;
}
