/**
 * The in-app architecture modal (ADR-0058): five tabs, each a hand-authored diagram in
 * public/svg/tech/ that carries both languages (l-en and l-es text pairs at the same coordinates) and
 * a bilingual explanation. The diagrams name the real modules; the explanations say what each part does.
 */
import type { ArchitectureConfig } from '@fasl-work/caos-app-shell';

export const ARCHITECTURE: ArchitectureConfig = {
  title_en: 'How OreFlow works',
  title_es: 'Cómo funciona OreFlow',
  tabs: [
    {
      id: 'app',
      en: 'The app and how it was built',
      es: 'La aplicación y cómo se construyó',
      svg: 'svg/tech/01-the-app.svg',
      body_en: 'OreFlow computes how a grinding and separation circuit trades recovery, concentrate grade, energy and water. An ore (its minerals, head grades, work index, liberation sizes and floatabilities), a plant (installed mill power, cyclone cluster, flotation cells) and an operating point of twelve inputs go through one engine that carries every stream as mass by size class and mineral, plus water, and closes the balance of every unit within 1e-9.\n\nIt was built in a fixed order: a research dossier checked against primary sources, a design whose every requirement names the test that fails when it is violated, the Python engine and its line-by-line TypeScript port, the bake that writes the method records and the learned lane, the gates (tests, an artifact checker, a browser gate whose screenshots are read) and the two deployments, each checked from outside.',
      body_es: 'OreFlow calcula cómo un circuito de molienda y separación intercambia recuperación, ley de concentrado, energía y agua. Un mineral (sus minerales, leyes de cabeza, índice de trabajo, tamaños de liberación y flotabilidades), una planta (potencia instalada, batería de ciclones, celdas de flotación) y un punto de operación de doce entradas pasan por un motor que lleva cada corriente como masa por clase de tamaño y mineral, más agua, y cierra el balance de cada unidad dentro de 1e-9.\n\nSe construyó en un orden fijo: un dossier de investigación contrastado con fuentes primarias, un diseño donde cada requisito nombra la prueba que falla cuando se viola, el motor en Python y su traducción línea a línea a TypeScript, el horneado que escribe los registros de métodos y la vía aprendida, los controles (pruebas, un verificador de artefactos, un control en navegador cuyas capturas se leen) y los dos despliegues, cada uno verificado desde fuera.',
    },
    {
      id: 'lanes',
      en: 'What runs where',
      es: 'Qué corre dónde',
      svg: 'svg/tech/02-lanes.svg',
      body_en: 'The offline bake runs on a workstation: twelve seeded case workers compute every variant\'s trace, optimizer and uncertainty records and the nominal Sobol record; the learning stage trains five models and a guard on 3072 states (with CUDA when present) and exports the networks to ONNX; the benchmark re-solves the published examples; the measured lanes read the GeoMet tests and the HZDR particles; and the artifact checks run last, so a failing check fails the bake.\n\nThe committed artifacts are copied into the site at build. In the browser, a moved control is validated by the same contract, solved by the TypeScript engine in a Web Worker, and drawn by the views; sweeps run only on request; the surrogate and its guard run with onnxruntime-web. The service on the VPS runs the Python engine behind the same contract and never trains or rewrites an artifact.',
      body_es: 'El horneado fuera de línea corre en una estación de trabajo: doce procesos sembrados calculan la traza y los registros de optimización e incertidumbre de cada variante y el registro de Sobol nominal; la etapa de aprendizaje entrena cinco modelos y un guardia sobre 3072 estados (con CUDA si existe) y exporta las redes a ONNX; el benchmark vuelve a resolver los ejemplos publicados; las vías medidas leen los ensayos GeoMet y las partículas HZDR; y las verificaciones de artefactos corren al final, así que una falla hace fallar el horneado.\n\nLos artefactos versionados se copian al sitio al compilar. En el navegador, un control movido se valida con el mismo contrato, lo resuelve el motor en TypeScript en un Web Worker y lo dibujan las vistas; los barridos corren solo cuando se piden; el sustituto y su guardia corren con onnxruntime-web. El servicio en el VPS ejecuta el motor en Python tras el mismo contrato y nunca entrena ni reescribe un artefacto.',
    },
    {
      id: 'web',
      en: 'The web app',
      es: 'La aplicación web',
      svg: 'svg/tech/03-web-app.svg',
      body_en: 'The build copies the baked artifacts, the exported networks and the WebAssembly runtime into the site, and writes a route file for every page with a fallback for deep links, so the same build serves the GitHub Pages path and the VPS root. The shared CAOS shell draws the header, the footer, the focus route and this modal.\n\nOn the workbench the rail holds the case, the variant and the contract\'s controls; the state lives in the URL, so it survives the trip to the focus view; every change is validated first, then solved in the worker, and only the newest reply is drawn. Six views draw the trace with interactive charts. The content pages lay out topics (prose, equations, limits, a figure, references) and read their tables and charts from the committed records; tests hold the browser engine and the page claims to the bake.',
      body_es: 'La compilación copia al sitio los artefactos horneados, las redes exportadas y el runtime WebAssembly, y escribe un archivo de ruta para cada página con un respaldo para enlaces profundos, así que la misma compilación sirve la ruta de GitHub Pages y la raíz del VPS. El shell compartido de CAOS dibuja el encabezado, el pie, la ruta de foco y este modal.\n\nEn el laboratorio el riel tiene el caso, la variante y los controles del contrato; el estado vive en la URL, así que sobrevive al viaje a la vista de foco; cada cambio se valida primero, luego se resuelve en el worker, y solo se dibuja la respuesta más nueva. Seis vistas dibujan la traza con gráficos interactivos. Las páginas de contenido ordenan temas (prosa, ecuaciones, límites, una figura, referencias) y leen sus tablas y gráficos desde los registros versionados; las pruebas sostienen el motor del navegador y las afirmaciones de las páginas contra el horneado.',
    },
    {
      id: 'science',
      en: 'The science',
      es: 'La ciencia',
      svg: 'svg/tech/04-the-science.svg',
      body_en: 'Every stream lives on one grid of 63 size classes. The crusher applies the Whiten matrix; the ball mill is a population balance with an energy-specific selection function through three perfect mixers; the hydrocyclones partition each particle class with a density-corrected cut. Root finders on the logarithms of the specific energy and of the cut size meet the target P80 and the design circulating load, and installed power caps the energy.\n\nSeparation follows the family: flotation banks with a rate constant from the bubble surface area flux and Savassi entrainment, the cleaner tails recycled to convergence; a gravity bleed for gold; LIMS drums for magnetite; a desliming cyclone for phosphate. Every unit is audited from its streams. The method records re-run the same engine: five lumped kinetic models fitted to a virtual batch test, a constrained optimum from six starts, Latin-hypercube uncertainty with Sobol indices, and a learned lane scored on plants it never saw.',
      body_es: 'Cada corriente vive en una malla de 63 clases de tamaño. El chancador aplica la matriz de Whiten; el molino de bolas es un balance poblacional con función de selección por energía específica a través de tres mezcladores perfectos; los hidrociclones separan cada clase de partícula con un corte corregido por densidad. Buscadores de raíces sobre los logaritmos de la energía específica y del corte cumplen el P80 objetivo y la carga circulante de diseño, y la potencia instalada limita la energía.\n\nLa separación sigue a la familia: bancos de flotación con una constante cinética desde el flujo de área superficial de burbujas y el arrastre de Savassi, con las colas del cleaner recirculadas hasta converger; una purga gravimétrica para el oro; tambores LIMS para la magnetita; un ciclón de deslamado para el fosfato. Cada unidad se audita desde sus corrientes. Los registros de métodos reejecutan el mismo motor: cinco modelos cinéticos agrupados ajustados a una prueba batch virtual, un óptimo con restricciones desde seis inicios, incertidumbre por hipercubo latino con índices de Sobol, y una vía aprendida evaluada en plantas que nunca vio.',
    },
    {
      id: 'contracts',
      en: 'The data contracts',
      es: 'Los contratos de datos',
      svg: 'svg/tech/05-data-contracts.svg',
      body_en: 'The operating contract declares every input once, with its unit, its bounds for each case, its step and the circuit families that use it, plus a cross-field rule for the desliming cut; its validator rejects an unknown case or input, an inapplicable input, a non-number, a non-finite or fractional value where it must be whole, and a value out of range, with the same codes in Python, in the browser and in the service. Every state it accepts is solved with closed balances.\n\nOne evaluation produces one trace. The bake writes one case artifact per case, with its definitions and six variants, bound by a manifest and an index built from the same run; the learning record, the networks and the benchmark carry the engine version and the contract digest too. The artifact checker recomputes every unit balance from the stored streams, the hashes and the record schemas, and rejects stray files, in the bake and again in CI.',
      body_es: 'El contrato de operación declara cada entrada una vez, con su unidad, sus límites para cada caso, su paso y las familias de circuito que la usan, más una regla entre campos para el corte de deslamado; su validador rechaza un caso o una entrada desconocidos, una entrada no aplicable, un valor que no es número, un valor no finito o fraccionario donde debe ser entero, y un valor fuera de rango, con los mismos códigos en Python, en el navegador y en el servicio. Cada estado que acepta se resuelve con balances cerrados.\n\nUna evaluación produce una traza. El horneado escribe un artefacto por caso, con sus definiciones y seis variantes, ligado por un manifiesto y un índice construidos en la misma corrida; el registro de aprendizaje, las redes y el benchmark también llevan la versión del motor y la huella del contrato. El verificador de artefactos recalcula cada balance por unidad desde las corrientes guardadas, los hashes y los esquemas de registro, y rechaza archivos sobrantes, en el horneado y otra vez en CI.',
    },
  ],
};
