/**
 * The in-app architecture modal (ADR-0058): five tabs, each a hand-authored diagram in
 * public/svg/tech/ that carries both languages (l-en and l-es text pairs at the same coordinates) and
 * a bilingual explanation. The diagrams name the real modules; the explanations say what each part does.
 */
import type { ArchitectureConfig } from '@fasl-work/caos-app-shell';

export const ARCHITECTURE: ArchitectureConfig = {
  title_en: 'How OreFlow works',
  title_es: 'Cómo funciona OreFlow',
  tabs: [
    {
      id: 'app',
      en: 'The app and how it was built',
      es: 'La aplicación y cómo se construyó',
      svg: 'svg/tech/01-the-app.svg',
      body_en: 'OreFlow computes how a grinding and separation circuit trades recovery, concentrate grade, energy and water. An ore (its minerals, head grades, work index, liberation sizes and floatabilities), a plant (installed mill power, cyclone cluster, flotation cells) and an operating point of thirteen inputs go through one engine that carries every stream as mass by size class and mineral, plus water, and closes the balance of every unit within 1e-9.\n\nIt was built in a fixed order: a research dossier checked against primary sources, a design whose every requirement names the test that fails when it is violated, the Python engine and its line-by-line TypeScript port, the precompute that writes the method records and the learned lane, the gates (tests, an artifact checker, a browser gate whose screenshots are read) and the deployment on its VPS, checked from outside.',
      body_es: 'OreFlow calcula cómo un circuito de molienda y separación intercambia recuperación, ley de concentrado, energía y agua. Un mineral (sus minerales, leyes de cabeza, índice de trabajo, tamaños de liberación y flotabilidades), una planta (potencia instalada, batería de ciclones, celdas de flotación) y un punto de operación de trece entradas pasan por un motor que lleva cada corriente como masa por clase de tamaño y mineral, más agua, y cierra el balance de cada unidad dentro de 1e-9.\n\nSe construyó en un orden fijo: un dossier de investigación contrastado con fuentes primarias, un diseño donde cada requisito nombra la prueba que falla cuando se viola, el motor en Python y su versión línea a línea en TypeScript, el precálculo que escribe los registros de métodos y la vía aprendida, los controles (pruebas, un verificador de artefactos, un control en navegador cuyas capturas se leen) y el despliegue en su VPS, verificado desde fuera.',
    },
    {
      id: 'lanes',
      en: 'What runs where',
      es: 'Qué corre dónde',
      svg: 'svg/tech/02-lanes.svg',
      body_en: 'The offline precompute runs on a workstation. The three measured lanes run first, each from its own script (the HZDR particles, the GeoMet locked-cycle tests and the iron-plant hours), so the precompute reads the fresh GeoMet record and checks all three. Then the contract, and the learning stage: it trains five models and a guard on 3072 states (with CUDA when present), exports the networks to ONNX and writes the optimizer\'s screen. Twelve seeded case workers compute every variant\'s trace, its optimizer record (at four weights of metal against energy, screened by that export in the target mode; the cut-mode searches run unscreened) and its uncertainty record, and the nominal Sobol record; the benchmark re-solves the published examples; the studies take each mechanism away and re-run the uncertainty at eight more seeds; the GeoMet samples run through the soft porphyry\'s circuit; the manifests bind every case; and the artifact checks run last, so a failing check fails the precompute.\n\nThe committed artifacts are copied into the site at build. In the browser, a moved control is validated by the same contract, solved by the TypeScript engine in a Web Worker, and drawn by the views; sweeps and the uncertainty re-run go to that worker only on request, and the optimizer runs in its own worker, which a newer run or a cancel terminates; the surrogate and its guard run with onnxruntime-web, and the screen runs the same networks in float64. The service on the VPS runs the Python engine behind the same contract and never trains or rewrites an artifact.',
      body_es: 'El precálculo fuera de línea corre en una estación de trabajo. Las tres vías medidas corren primero, cada una con su propio script (las partículas HZDR, los ensayos de ciclo cerrado GeoMet y las horas de la planta de hierro), así que el precálculo lee el registro GeoMet recién escrito y verifica los tres. Luego el contrato y la etapa de aprendizaje: entrena cinco modelos y un guardia sobre 3072 estados (con CUDA si existe), exporta las redes a ONNX y escribe el filtro del optimizador. Doce procesos sembrados calculan la traza de cada variante, su registro de optimización (con cuatro pesos del metal contra la energía, filtrado por esa exportación en el modo objetivo; las búsquedas del modo de corte corren sin filtro) y su registro de incertidumbre, y el registro de Sobol nominal; el benchmark vuelve a resolver los ejemplos publicados; los estudios quitan cada mecanismo y repiten la incertidumbre con ocho semillas más; las muestras GeoMet corren en el circuito del pórfido blando; los manifiestos ligan cada caso; y las verificaciones de artefactos corren al final, así que una falla hace fallar el precálculo.\n\nLos artefactos versionados se copian al sitio al compilar. En el navegador, un control movido se valida con el mismo contrato, lo resuelve el motor en TypeScript en un Web Worker y lo dibujan las vistas; los barridos y la repetición de la incertidumbre van a ese worker solo cuando se piden, y el optimizador corre en su propio worker, que una corrida más nueva o una cancelación termina; el sustituto y su guardia corren con onnxruntime-web, y el filtro corre las mismas redes en float64. El servicio en el VPS ejecuta el motor en Python tras el mismo contrato y nunca entrena ni reescribe un artefacto.',
    },
    {
      id: 'web',
      en: 'The web app',
      es: 'La aplicación web',
      svg: 'svg/tech/03-web-app.svg',
      body_en: 'The build copies the precomputed artifacts, the exported networks and the WebAssembly runtime into the site, and the service on the VPS answers every page route with the app, so a deep link opens its page. The shared CAOS shell draws the header, the footer, the focus route and this modal.\n\nOn the workbench the rail holds the source (a synthetic case, a GeoMet sample or an iron-plant hour), the case, the variant and the contract\'s controls; the state lives in the URL, so it survives the trip to the focus view; every change is validated first, then solved in the worker, and only the newest reply is drawn. A sample runs through the engine; a plant hour is shown, never simulated. Six views draw the trace with interactive charts. The content pages lay out topics (prose, equations, limits, a figure, references) and read their tables and charts from the committed records; tests hold the browser engine and the page claims to the precompute.',
      body_es: 'La compilación copia al sitio los artefactos precalculados, las redes exportadas y el runtime WebAssembly, y el servicio en el VPS responde cada ruta de página con la aplicación, así que un enlace profundo abre su página. El shell compartido de CAOS dibuja el encabezado, el pie, la ruta de foco y este modal.\n\nEn el simulador el riel tiene la fuente (un caso sintético, una muestra GeoMet o una hora de la planta de hierro), el caso, la variante y los controles del contrato; el estado vive en la URL, así que sobrevive al viaje a la vista de foco; cada cambio se valida primero, luego se resuelve en el worker, y solo se dibuja la respuesta más nueva. Una muestra corre por el motor; una hora de planta se muestra y nunca se simula. Seis vistas dibujan la traza con gráficos interactivos. Las páginas de contenido ordenan temas (prosa, ecuaciones, límites, una figura, referencias) y leen sus tablas y gráficos desde los registros versionados; las pruebas sostienen el motor del navegador y las afirmaciones de las páginas contra el precálculo.',
    },
    {
      id: 'science',
      en: 'The science',
      es: 'La ciencia',
      svg: 'svg/tech/04-the-science.svg',
      body_en: 'Every stream lives on one grid of 63 size classes. The crusher applies the Whiten matrix; the ball mill is a population balance with an energy-specific selection function through three perfect mixers; the hydrocyclones partition each particle class with a density-corrected cut. Root finders on the logarithms of the specific energy and of the cut size meet the target P80 and the design circulating load, and installed power caps the energy; in the cut mode the cut is set, the mill draws its installed power, and the P80 and the load follow. In the gold case a bleed of the cyclone underflow passes the gravity unit inside the loop, and its tail returns to the mill.\n\nSeparation follows the family: flotation banks with a rate constant from the bubble surface area flux and Savassi entrainment, as a rougher, an optional regrind, a cleaner and an optional recleaner, the cleaner tails returned to the rougher feed and the recleaner tails to the cleaner feed, both converged to 1e-10 t/h and 1e-12 relative; LIMS drums for magnetite; a desliming cyclone for phosphate. Every unit is audited from its streams. The method records re-run the same engine: five lumped kinetic models fitted to a virtual batch test, a pattern search with a progressive barrier from six starts, screened by the learned lane in the target mode and run at four weights of metal against energy, SplitMix64 Latin-hypercube uncertainty with Sobol indices, and a learned lane scored on plants it never saw.',
      body_es: 'Cada corriente vive en una malla de 63 clases de tamaño. El chancador aplica la matriz de Whiten; el molino de bolas es un balance poblacional con función de selección por energía específica a través de tres mezcladores perfectos; los hidrociclones separan cada clase de partícula con un corte corregido por densidad. Buscadores de raíces sobre los logaritmos de la energía específica y del corte cumplen el P80 objetivo y la carga circulante de diseño, y la potencia instalada limita la energía; en el modo de corte el corte se fija, el molino consume su potencia instalada, y el P80 y la carga resultan. En el caso de oro una purga de la descarga del ciclón pasa por la unidad gravimétrica dentro del circuito, y su relave vuelve al molino.\n\nLa separación sigue a la familia: bancos de flotación con una constante cinética desde el flujo de área superficial de burbujas y el arrastre de Savassi, como un rougher, una remolienda opcional, una limpieza y una relimpieza opcional, con las colas de limpieza devueltas a la alimentación rougher y las de relimpieza a la de limpieza, ambas convergidas a 1e-10 t/h y 1e-12 relativo; tambores LIMS para la magnetita; un ciclón de deslamado para el fosfato. Cada unidad se audita desde sus corrientes. Los registros de métodos reejecutan el mismo motor: cinco modelos cinéticos agrupados ajustados a una prueba batch virtual, una búsqueda por patrones con barrera progresiva desde seis inicios, filtrada por la vía aprendida en el modo objetivo y corrida con cuatro pesos del metal contra la energía, incertidumbre por hipercubo latino SplitMix64 con índices de Sobol, y una vía aprendida evaluada en plantas que nunca vio.',
    },
    {
      id: 'contracts',
      en: 'The data contracts',
      es: 'Los contratos de datos',
      svg: 'svg/tech/05-data-contracts.svg',
      body_en: 'The operating contract declares every input once, with its unit, its bounds for each case, its step and the circuit families that use it, plus a cross-field rule for the desliming cut; its validator rejects an unknown case or input, an inapplicable input, a non-number, a non-finite or fractional value where it must be whole, and a value out of range, with the same codes in Python, in the browser and in the service. Every state it accepts is solved with closed balances.\n\nOne evaluation produces one trace. The precompute writes one case artifact per case, with its definitions and eight variants, bound by a manifest and an index built from the same run. Every engine record (the cases, the manifests, the index, the learning record, the benchmark, the studies, the real samples and the validation record) carries the engine version and the contract digest; the exported networks are bound to the learning record by their byte counts, and the measured lanes\' records carry neither. The artifact checker recomputes every unit balance from the stored streams, the hashes and the record schemas, and rejects stray files, in the precompute and again in CI.',
      body_es: 'El contrato de operación declara cada entrada una vez, con su unidad, sus límites para cada caso, su paso y las familias de circuito que la usan, más una regla entre campos para el corte de deslamado; su validador rechaza un caso o una entrada desconocidos, una entrada no aplicable, un valor que no es número, un valor no finito o fraccionario donde debe ser entero, y un valor fuera de rango, con los mismos códigos en Python, en el navegador y en el servicio. Cada estado que acepta se resuelve con balances cerrados.\n\nUna evaluación produce una traza. El precálculo escribe un artefacto por caso, con sus definiciones y ocho variantes, ligado por un manifiesto y un índice construidos en la misma corrida. Cada registro del motor (los casos, los manifiestos, el índice, el registro de aprendizaje, el benchmark, los estudios, las muestras reales y el registro de validación) lleva la versión del motor y la huella del contrato; las redes exportadas quedan ligadas al registro de aprendizaje por su tamaño en bytes, y los registros de las vías medidas no llevan ninguna. El verificador de artefactos recalcula cada balance por unidad desde las corrientes guardadas, los hashes y los esquemas de registro, y rechaza archivos sobrantes, en el precálculo y otra vez en CI.',
    },
  ],
};
