import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router';
import { Activity, Atom, Beaker, Gauge, Rotate3D, Sparkles, Waves } from 'lucide-react';
import { useShellLang } from '@fasl-work/caos-app-shell';
import { loadBenchmark, loadCase, loadIndex } from '../api/artifacts';
import type { Benchmark, CaseArtifact, CaseIndex, Params, Variant } from '../lib/contract.types';
import { simulateLive } from '../live/engine';
import { Chart, MetricCard } from '../components/Charts';
import Flowsheet from '../components/Flowsheet';

const labels: Record<string, [string, string, string, number, number, number]> = {
  feed_tph: ['Throughput', 'Tratamiento', 't/h', 100, 1800, 10],
  grind_p80_um: ['Grind P80', 'P80 molienda', 'µm', 35, 500, 5],
  classifier_cut_um: ['Classifier cut', 'Corte clasificador', 'µm', 25, 400, 5],
  flotation_time_min: ['Residence time', 'Tiempo residencia', 'min', 4, 55, 1],
  reagent_gpt: ['Collector dose', 'Reactivo colector', 'g/t', 20, 600, 5],
  air_rate_m3_min: ['Air rate', 'Aire', 'm³/min', .2, 6, .1],
};
const parameterKeys = Object.keys(labels);

export default function Workbench() {
  const es = useShellLang() === 'es';
  const [index, setIndex] = useState<CaseIndex | null>(null); const [benchmark, setBenchmark] = useState<Benchmark | null>(null); const [caseData, setCaseData] = useState<CaseArtifact | null>(null); const [caseId, setCaseId] = useState(''); const [variantId, setVariantId] = useState('nominal'); const [params, setParams] = useState<Params | null>(null); const [angleStep, setAngleStep] = useState(8); const [activeStage, setActiveStage] = useState('grind'); const [running, setRunning] = useState(false); const [error, setError] = useState('');
  useEffect(() => { Promise.all([loadIndex(), loadBenchmark()]).then(([ix, b]) => { setIndex(ix); setBenchmark(b); setCaseId(ix.cases[0]?.case_id ?? ''); }).catch(e => setError(String(e))); }, []);
  useEffect(() => { if (!caseId) return; setRunning(true); loadCase(caseId).then(data => { setCaseData(data); const variant = data.variants.find(v => v.id === variantId) ?? data.variants[0]; setVariantId(variant.id); setParams(variant.params); }).catch(e => setError(String(e))).finally(() => setRunning(false)); }, [caseId]);
  const selectedVariant: Variant | undefined = caseData?.variants.find(v => v.id === variantId);
  const replayParams = selectedVariant?.params ?? params;
  const stateParams = params ?? replayParams;
  const dirty = Boolean(selectedVariant && stateParams && parameterKeys.some(key => Math.abs((stateParams[key] ?? 0) - (selectedVariant.params[key] ?? 0)) > 1e-8));
  const live = useMemo(() => stateParams && caseId ? simulateLive(stateParams, caseId) : null, [stateParams, caseId]);
  const shown = live ?? selectedVariant?.trace;
  const activeMethods = selectedVariant?.method_outputs ?? [];
  const categoryCases = useMemo(() => { const map: Record<string, CaseIndex['cases']> = {}; index?.cases.forEach(c => (map[c.category] ??= []).push(c)); return map; }, [index]);
  const chooseVariant = (id: string) => { const v = caseData?.variants.find(item => item.id === id); if (v) { setVariantId(id); setParams(v.params); } };
  const changeParam = (key: string, value: number) => setParams(old => old ? { ...old, [key]: value } : old);
  const reset = () => { if (selectedVariant) setParams(selectedVariant.params); };
  const stageCopy: Record<string, [string, string, string]> = { feed: ['Feed characterization', 'Caracterización de alimentación', 'Particle shape, grade and size distribution anchor the circuit.'], crush: ['Whiten breakage', 'Ruptura Whiten', 'Crusher product P80 is a response, not a free label.'], grind: ['Population balance', 'Balance poblacional', 'Selection and breakage create the ground-size response.'], classify: ['Cyclone partition', 'Partición ciclónica', 'The cut-size and imperfection shape overflow.'], float: ['Kinetic flotation', 'Flotación cinética', 'Fast and slow mineral populations expose residence-time trade-offs.'], product: ['Concentrate', 'Concentrado', 'Grade, recovery and mass pull close the balance.'], tail: ['Tailings', 'Relaves', 'The remaining valuable mineral is reported, not discarded.'] };
  const stage = stageCopy[activeStage] ?? stageCopy.grind;
  if (error) return <div className="of-page"><div className="of-error">{error}</div></div>;
  return <div className="of-page of-workbench">
    <section className="of-hero"><div><div className="of-eyebrow"><span className="of-signal" /> CAOS RESEARCH / PROCESS INTELLIGENCE</div><h1>Ore<span>Flow</span></h1><p className="of-hero-lede">{es ? 'Un laboratorio visual para descubrir cómo la fragmentación, clasificación, flotación y aprendizaje cambian la decisión de proceso.' : 'A visual laboratory for discovering how fragmentation, classification, flotation and learning reshape the process decision.'}</p><div className="of-hero-actions"><Link className="of-primary" to="/introduction">{es ? 'Leer la investigación' : 'Enter the research'} <span>↗</span></Link><Link className="of-ghost" to="/benchmark">{es ? 'Ver evidencia' : 'Inspect evidence'}</Link></div></div><div className="of-hero-orbit"><div className="of-orbit-core"><Atom size={26} /><strong>19</strong><small>methods</small></div><i className="orbit orbit-a" /><i className="orbit orbit-b" /><i className="orbit orbit-c" /></div></section>
    <section className="of-control-bar"><label>{es ? 'Caso de estudio' : 'Study case'}<select value={caseId} onChange={e => setCaseId(e.target.value)}>{Object.entries(categoryCases).map(([cat, cases]) => <optgroup key={cat} label={cat}>{cases?.map(c => <option key={c.case_id} value={c.case_id}>{c.title}</option>)}</optgroup>)}</select></label><label>{es ? 'Variante' : 'Variant'}<select value={variantId} onChange={e => chooseVariant(e.target.value)}>{caseData?.variants.map(v => <option key={v.id} value={v.id}>{v.label}</option>)}</select></label><div className="of-lane"><span className={dirty ? 'live' : 'replay'}>{dirty ? 'LIVE ENGINE' : 'REPLAY ARTIFACT'}</span><small>{running ? (es ? 'cargando...' : 'loading...') : `${index?.n_cases ?? 0} cases · ${benchmark?.variant_count ?? 0} variants`}</small></div></section>
    <section className="of-workspace"><div className="of-stage-panel"><div className="of-panel-top"><div><span className="of-kicker">{caseData?.category ?? 'loading'} / {variantId}</span><h2>{caseData?.title ?? 'OreFlow process circuit'}</h2><p>{caseData?.description ?? (es ? 'Cargando artefacto científico...' : 'Loading scientific artifact...')}</p></div><button className="of-reset" type="button" onClick={reset} disabled={!dirty}>Reset</button></div><Flowsheet angleStep={angleStep} active={activeStage} onSelect={setActiveStage} /><div className="of-stage-readout"><div className="of-stage-icon"><Waves size={20} /></div><div><span>{es ? stage[1] : stage[0]}</span><strong>{es ? 'lectura vinculada al estado activo' : stage[2]}</strong></div><b>{activeStage.toUpperCase()}</b></div></div>
      <aside className="of-side-panel"><div className="of-side-head"><span className="of-kicker">{es ? 'control del proceso' : 'process control'}</span><h2>{es ? 'Mueve el circuito' : 'Move the circuit'}</h2><p>{es ? 'Los controles cambian el motor local y marcan el replay como obsoleto.' : 'Controls change the local engine and mark replay as stale.'}</p></div><div className="of-sliders">{parameterKeys.map(key => { const [en, spanish, unit, min, max, step] = labels[key]; const value = stateParams?.[key] ?? min; return <label className="of-slider" key={key}><span><b>{es ? spanish : en}</b><em>{value.toFixed(step < 1 ? 1 : 0)} {unit}</em></span><input aria-label={es ? spanish : en} type="range" min={min} max={max} step={step} value={value} onChange={e => changeParam(key, Number(e.target.value))} /><i style={{ width: `${((value - min) / (max - min)) * 100}%` }} /></label>; })}<label className="of-slider of-angle"><span><b><Rotate3D size={14} /> {es ? 'Ángulo de paso' : 'Angle step'}</b><em>{angleStep}°</em></span><input type="range" min="1" max="24" step="1" value={angleStep} onChange={e => setAngleStep(Number(e.target.value))} /><i style={{ width: `${(angleStep / 24) * 100}%` }} /></label></div><div className="of-engine-note"><Sparkles size={15} /><span>{dirty ? (es ? 'La respuesta vive en el navegador.' : 'Response is running in the browser.') : (es ? 'El artefacto está firmado por el pipeline.' : 'Artifact is signed by the pipeline.')}</span></div></aside></section>
    {shown && <section className="of-metrics"><MetricCard label={es ? 'Recuperación' : 'Recovery'} value={shown.metrics.recovery_pct.toFixed(1)} unit="%" tone="teal" detail="rougher valuable mineral" /><MetricCard label={es ? 'Ley concentrado' : 'Concentrate grade'} value={shown.metrics.concentrate_grade_pct.toFixed(2)} unit="%" tone="violet" detail="mass balance closure" /><MetricCard label={es ? 'Energía específica' : 'Specific energy'} value={shown.metrics.specific_energy_kwh_t.toFixed(1)} unit="kWh/t" tone="gold" detail="Bond + surface laws" /><MetricCard label={es ? 'Agua de planta' : 'Plant water'} value={shown.metrics.water_use_m3_h.toFixed(0)} unit="m³/h" tone="cyan" detail="throughput × water" /></section>}
    {shown && <section className="of-charts-grid"><Chart title={es ? 'Evolución de tamaño' : 'Size evolution'} subtitle={es ? 'Distribución acumulativa pasante' : 'Cumulative passing distribution'} labels={shown.size_um.map(v => `${Math.round(v)} µm`)} series={[{ name: es ? 'Alimentación' : 'Feed', color: '#f0ba64', values: shown.feed_psd }, { name: es ? 'Triturado' : 'Crushed', color: '#78b6aa', values: shown.crushed_psd }, { name: es ? 'Molienda' : 'Ground', color: '#c586e8', values: shown.ground_psd }, { name: es ? 'Overflow' : 'Overflow', color: '#80d3e7', values: shown.overflow_psd }]} format={v => `${(v * 100).toFixed(0)}%`} /><Chart title={es ? 'Cinética de flotación' : 'Flotation kinetics'} subtitle={es ? 'Recuperación acumulada frente a residencia' : 'Cumulative recovery against residence'} labels={shown.flotation_recovery.map((_, i) => `${(i / 95 * (stateParams?.flotation_time_min ?? 20)).toFixed(0)} min`)} series={[{ name: es ? 'Recuperación' : 'Recovery', color: '#6cd5c6', values: shown.flotation_recovery.map(v => v * 100) }]} format={v => `${v.toFixed(1)}%`} /></section>}
     <section className="of-methods"><div className="of-section-head"><div><span className="of-kicker">{es ? 'registro de métodos' : 'method ledger'}</span><h2>{es ? 'Clásico → aprendido → frontera' : 'Classical → learned → frontier'}</h2></div><Link to="/methodology">{es ? 'Leer supuestos' : 'Read assumptions'} ↗</Link></div><div className="of-method-grid">{activeMethods.slice(0, 10).map(method => <div className="of-method" key={method.id}><div><span className={`of-tier ${method.tier}`}>{method.tier}</span><h3>{method.name}</h3></div><strong>{method.value.toFixed(2)}<small>{method.unit}</small></strong><div className="of-method-bar"><i style={{ width: `${Math.min(100, Math.abs(method.value) / Math.max(1, shown?.metrics.recovery_pct ?? 100) * 100)}%` }} /></div></div>)}</div><div className="of-method-foot"><span><Beaker size={15} /> {activeMethods.length || 19} {es ? 'métodos ejecutados por variante' : 'methods executed per variant'}</span><Link to="/implementation">{es ? 'Ver pipeline y modelos' : 'Open pipeline and models'} ↗</Link></div></section>
    <section className="of-bottom-strip"><div><Gauge size={18} /><span><b>{benchmark?.case_count ?? 12}</b> cases</span></div><div><Activity size={18} /><span><b>{benchmark?.variant_count ?? 72}</b> variant runs</span></div><div><Sparkles size={18} /><span><b>{benchmark?.method_count ?? 19}</b> models</span></div><div><Link to="/experiments">{es ? 'Explorar experimentos' : 'Explore experiments'} ↗</Link></div></section>
  </div>;
}
